const elementBody = document.querySelector('body');                                    // Body
const elementButtonUp = document.querySelector('.button-up');                          // Кнопка Вверх
const elementHeader = document.querySelector('.header')                                // header
const elementMain = document.querySelector('.main');                                   // Страница Main
const elementMainContainer = document.querySelector('.main-container-header-contacts');// Главный контейнер
const elementButtonFeedBack = document.querySelectorAll('.contact-feedback-text');     // Кнопка Обратная связь
const elementFormFeedback = document.querySelector('.container-form-feedback');        // Контейнер формы Обратная связь
const elementFormRequest = document.querySelector('.container-form-request');          // Контейнер формы Оставить заявку
const elementButtonCloseForm = document.querySelectorAll('.box-form-h-text-close');    // Контейнер кнопки закрыть на форме
const elementTransLink = document.querySelector('.h-cont-trans-link');                 // Ссылка на открытие формы Оставить заявку
const elementPrice = document.querySelector('.price')                                  // Кнопка Прайс
const elementPagePrice = document.querySelector('.bg-container-price');                // Страница Прайс
const elementContainerTitle = document.querySelector('.bg-container-title')            // Контейнер с большой картинкой
const elementContainerHeaderLogo = document.querySelector('.container-header-logo')    // Контейнер с рисунком быка и фразой Домашний переезд
const elementLinkMain = document.querySelector('.navigation-menu-item-link')           // Ссылка на хлебных крошках Главная
const elementButtonRequest = document.querySelector('.box-button-price')               // Кнопка Оставить заявку
const elementMenuPrice = document.querySelectorAll('.box-item-pr-veh-mass')            // Кнопки меню страницы Price
const elementSectionMass = document.querySelectorAll('.box-price')                     // Секции с весами
const elementForms = document.querySelectorAll('.form-request')                        // Формы
const elementbgHeaderLogo = document.querySelector('.bg-box-header-logo');             // Контейнер с быком и текстом
const elementContainerHeader = document.querySelector('.container-header');            // Контейнер с контактами и обратной связью
const elementmvButtonMenu = document.querySelector('.mv-button-menu');                 // Кнопка Меню в мобильной версии
const elementArticleContent = document.querySelectorAll('.article-content')            // Коллекция картинок с услугами
const elementVehicleFleet = document.querySelectorAll('.container-vehicle-fleet')      // Коллекция грузовиков
const elementItemPrVeMass = document.querySelectorAll('.item-price-veh-mass')          // Коллекция элементов с весами в прайсе
const elementBoxPrMass = document.querySelectorAll('.box-item-pr-veh-mass')            // Коллекция названий весов в прайсе
let numberActiveSection = 0;                                                           // Номер активной секции в прайсе